name: Deploy Full App to AWS

on:
  push:
    branches: [ main ]
    paths:
      - 'Backend/**'
      - 'Frontend/**'
  # Déclenchement automatique après le succès du training
  workflow_run:
    workflows: ["Model Training Pipeline (CT)"]
    types: [completed]
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check for changes in folders
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            backend:
              - 'Backend/**'
            frontend:
              - 'Frontend/**'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # --- SECTION BACKEND ---
      - name: Build and Push Backend
        if: ${{ steps.filter.outputs.backend == 'true' || github.event_name == 'workflow_run' }}
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_BACKEND_REPO }} 
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Backend/Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy Backend to App Runner
        if: ${{ steps.filter.outputs.backend == 'true' || github.event_name == 'workflow_run' }}
        run: |
          # On récupère l'ARN via le nom du service
          SERVICE_ARN=$(aws apprunner list-services --query "ServiceSummaryList[?ServiceName=='service-backend-g1-mg04'].ServiceArn" --output text)
          aws apprunner start-deployment --service-arn $SERVICE_ARN

      # --- SECTION FRONTEND ---
      - name: Build and Push Frontend
        if: ${{ steps.filter.outputs.frontend == 'true' }}
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_FRONTEND_REPO }}
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Frontend/Dockerfile ./Frontend
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy Frontend to App Runner
        if: ${{ steps.filter.outputs.frontend == 'true' }}
        run: |
          SERVICE_ARN=$(aws apprunner list-services --query "ServiceSummaryList[?ServiceName=='service-frontend-g1-mg04'].ServiceArn" --output text)
          aws apprunner start-deployment --service-arn $SERVICE_ARN