name: Deploy Full App to AWS

on:
  push:
    branches: [ main ]
    paths:
      - 'Backend/**'
      - 'Frontend/**'
  workflow_run:
    workflows: ["Model Training Pipeline (CT)"]
    types: [completed]
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check for changes in folders
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            backend:
              - 'Backend/**'
            frontend:
              - 'Frontend/**'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download Model from S3
        if: ${{ steps.filter.outputs.backend == 'true' || github.event_name == 'workflow_run' }}
        run: |
          mkdir -p Backend/app/model
          aws s3 cp s3://${{ secrets.S3_BUCKET_NAME }}/models/best_model.joblib Backend/app/model/best_model.joblib
          echo "✅ Modèle récupéré de S3 et placé dans Backend/app/model/"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Backend
        if: ${{ steps.filter.outputs.backend == 'true' || github.event_name == 'workflow_run' }}
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_BACKEND_REPO }} 
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Backend/Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Build and Push Frontend
        if: steps.filter.outputs.frontend == 'true'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_FRONTEND_REPO }}
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Frontend/Dockerfile ./Frontend
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG